name: "release"

on:
  push:
    branches: [beta, alpha, 8.x]

jobs:
  check:
    uses: vodyani/workflows/.github/workflows/check.yml@master
    with:
      enable_test: false

  semantic_release:
    needs: [check]
    uses: vodyani/workflows/.github/workflows/semantic-release.yml@master
    secrets:
      NPM_CI_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      enable_build: true
